package id.langkahberdua.app;
import android.net.Uri;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

final class CsvBackup {
 final MainActivity a;CsvBackup(MainActivity a){this.a=a;}
 void export(Uri uri)throws Exception {try(OutputStream out=a.getContentResolver().openOutputStream(uri)){StringBuilder b=new StringBuilder("\uFEFFJudul,Nominal,Jenis,Tanggal,Akses,Status,ID,RincianStruk\r\n");for(Store.Row row:a.store.all()){JSONObject r=row.display();if(r.optBoolean("deleted")||r.optString("kind").equals("shopping"))continue;b.append(Csv.cell(r.optString("title"))).append(',').append(r.optLong("amount")).append(',').append(r.optString("kind")).append(',').append(r.optString("date")).append(',').append(r.optString("visibility")).append(',').append(row.pending==null?"tersimpan":"menunggu").append(',').append(row.id).append(',').append(Csv.cell(r.optString("receipt"))).append("\r\n");}out.write(b.toString().getBytes(StandardCharsets.UTF_8));a.message("CSV tersimpan. Foto bukti tidak termasuk CSV.");}}
 void importOld(Uri uri)throws Exception {String content;try(InputStream in=a.getContentResolver().openInputStream(uri);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){out.write(b,0,n);if(out.size()>5000000)throw new IOException("CSV terlalu besar");}content=out.toString("UTF-8").replace("\uFEFF","");}List<List<String>> rows=Csv.read(content);if(rows.isEmpty()||!rows.get(0).equals(Arrays.asList("Judul","Nominal","Jenis","Tanggal")))throw new IOException("Pilih CSV ekspor versi 0.3 (empat kolom)");List<JSONObject> records=new ArrayList<>();String digest=android.util.Base64.encodeToString(java.security.MessageDigest.getInstance("SHA-256").digest(content.getBytes(StandardCharsets.UTF_8)),android.util.Base64.NO_WRAP);for(int i=1;i<rows.size();i++){List<String> r=rows.get(i);if(r.size()==1&&r.get(0).isEmpty())continue;if(r.size()!=4||r.get(0).isEmpty()||r.get(0).length()>120||ReceiptParser.money(r.get(1))==null||ReceiptParser.money(r.get(1))<=0||!Arrays.asList("income","expense").contains(r.get(2))||!ReceiptParser.isoDate(r.get(3)).equals(r.get(3)))throw new IOException("Baris "+(i+1)+" tidak valid");JSONObject record=Store.make(r.get(0),ReceiptParser.money(r.get(1)),r.get(2),r.get(3),"private","Impor versi 0.3","Belanja","");record.put("uuid",UUID.nameUUIDFromBytes((digest+"\nROW:"+i).getBytes(StandardCharsets.UTF_8)).toString());records.add(record);}a.confirm("Impor "+records.size()+" transaksi sebagai catatan pribadi? Impor ulang file identik akan dilewati. File berbeda dengan transaksi sama tetap perlu diperiksa.",()->{int n=0;for(JSONObject r:records)if(a.store.get(r.optString("uuid"))==null){a.store.save(r,"","");n++;}a.message(n+" transaksi diimpor");a.screen();});}
}
