package id.langkahberdua.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.net.Uri;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.text.NumberFormat;
import java.util.*;
import java.util.concurrent.*;

/** Native Android views, SQLite and on-device OCR. No WebView. */
public class MainActivity extends Activity implements ReceiptScanner.Callback {
 Store store;Cloud cloud;ReceiptScanner scanner;LinearLayout body;TextView statusView;
 String tab="Beranda",status="Google Sheets belum dihubungkan";
 boolean showingSplash=true,resumed=false;volatile boolean busy=false;int dialogs=0;
 final int sage=Color.rgb(97,124,102),ink=Color.rgb(38,60,48),cream=Color.rgb(247,244,235);
 final Handler handler=new Handler(Looper.getMainLooper());final ExecutorService worker=Executors.newSingleThreadExecutor();
 final Runnable poll=new Runnable(){public void run(){if(resumed){sync();handler.postDelayed(this,30000);}}};
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 @Override public void onCreate(Bundle s){super.onCreate(s);store=new Store(this);cloud=new Cloud(this);scanner=new ReceiptScanner(this,this);if(s!=null){tab=s.getString("tab","Beranda");String path=s.getString("camera","");if(!path.isEmpty())scanner.cameraFile=new File(path);showingSplash=false;screen();}else splash();}
 @Override protected void onResume(){super.onResume();resumed=true;handler.removeCallbacks(poll);handler.postDelayed(poll,3000);}
 @Override protected void onPause(){resumed=false;handler.removeCallbacks(poll);super.onPause();}
 @Override protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putString("tab",tab);if(scanner.cameraFile!=null)b.putString("camera",scanner.cameraFile.getPath());}
 @Override protected void onDestroy(){handler.removeCallbacksAndMessages(null);worker.execute(()->store.db.close());worker.shutdown();super.onDestroy();}
 TextView text(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(ink);t.setPadding(0,dp(7),0,dp(7));return t;}
 LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 void rounded(View v,int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(18));v.setBackground(d);}
 Button button(String title,Runnable action){Button b=new Button(this);b.setText(title);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setMinHeight(dp(48));rounded(b,sage);b.setOnClickListener(v->action.run());return b;}
 LinearLayout form(){LinearLayout f=column();f.setPadding(dp(20),0,dp(20),dp(16));return f;}
 EditText input(LinearLayout f,String label,String value,boolean number){f.addView(text(label,14));EditText e=new EditText(this);e.setSingleLine(true);e.setText(value);e.setTextSize(16);if(number)e.setInputType(2);f.addView(e);return e;}
 AlertDialog dialog(String title,LinearLayout form,String action){ScrollView scroll=new ScrollView(this);scroll.addView(form);AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setView(scroll).setPositiveButton(action,null).setNegativeButton("Batal",null).create();show(d);return d;}
 void show(AlertDialog d){dialogs++;d.setOnDismissListener(v->{dialogs--;if(!isDestroyed()&&!showingSplash)screen();});d.show();d.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);}
 @Override public void message(String s){runOnUiThread(()->{if(!isDestroyed())Toast.makeText(this,s==null?"Terjadi kesalahan. Coba lagi.":s,Toast.LENGTH_LONG).show();});}
 void splash(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(sage);ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);
  try{String uri=getSharedPreferences("settings",0).getString("photo","");if(!uri.isEmpty())try(InputStream in=getContentResolver().openInputStream(Uri.parse(uri))){BitmapFactory.Options o=new BitmapFactory.Options();o.inSampleSize=4;image.setImageBitmap(BitmapFactory.decodeStream(in,null,o));}}catch(Exception ignored){}
  root.addView(image,new FrameLayout.LayoutParams(-1,-1));LinearLayout copy=column();copy.setGravity(Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);copy.setPadding(dp(24),dp(40),dp(24),dp(90));copy.setBackgroundColor(0x660F2419);TextView title=text("Langkah Berdua",32);title.setTypeface(Typeface.SERIF,Typeface.BOLD);title.setTextColor(Color.WHITE);copy.addView(title);TextView motto=text("Semoga bisa disemogakan",20);motto.setTypeface(Typeface.SERIF,Typeface.ITALIC);motto.setTextColor(Color.WHITE);copy.addView(motto);copy.addView(new ProgressBar(this),new LinearLayout.LayoutParams(dp(30),dp(30)));root.addView(copy,new FrameLayout.LayoutParams(-1,-1));setContentView(root);handler.postDelayed(()->{showingSplash=false;screen();},1800);
 }
 String money(long n){return NumberFormat.getCurrencyInstance(new Locale("id","ID")).format(n).replace(",00","");}
 String today(){return new java.text.SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).format(new Date());}
 String prettyDate(String iso){try{return new java.text.SimpleDateFormat("d MMMM yyyy",new Locale("id","ID")).format(new java.text.SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).parse(iso));}catch(Exception e){return iso;}}
 void screen(){if(isDestroyed())return;LinearLayout root=column();root.setBackgroundColor(cream);root.setPadding(dp(18),dp(10),dp(18),dp(6));root.addView(text("LANGKAH BERDUA",12));TextView heading=text(tab,29);heading.setTypeface(Typeface.SERIF,Typeface.BOLD);root.addView(heading);statusView=text(status+pendingLabel(),12);root.addView(statusView);ScrollView scroll=new ScrollView(this);body=column();scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  switch(tab){case "Beranda":home();break;case "Transaksi":transactions();break;case "Rencana":plans();break;case "Belanja":shopping();break;default:settings();}
  LinearLayout nav=new LinearLayout(this);for(String name:new String[]{"Beranda","Transaksi","Rencana","Belanja","Pengaturan"}){TextView t=text(name,11);t.setGravity(Gravity.CENTER);t.setMinHeight(dp(56));if(name.equals(tab)){rounded(t,0xFFE2E9DD);t.setTypeface(null,Typeface.BOLD);}t.setOnClickListener(v->{tab=name;screen();});nav.addView(t,new LinearLayout.LayoutParams(0,-2,1));}root.addView(nav);setContentView(root);
 }
 String pendingLabel(){int n=store.pendingCount();return n>0?" · "+n+" menunggu":"";}
 void card(String title,String value){LinearLayout c=column();rounded(c,Color.WHITE);c.setPadding(dp(18),dp(10),dp(18),dp(14));c.addView(text(title,14));TextView v=text(value,26);v.setTypeface(null,Typeface.BOLD);c.addView(v);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(8),0,dp(12));body.addView(c,p);}
 void home(){card("Saldo catatan yang telah tersimpan",money(store.sum("income")-store.sum("expense")));card("Pemasukan",money(store.sum("income")));card("Pengeluaran",money(store.sum("expense")));body.addView(button("Tambah pengeluaran",()->edit(null,"expense")));body.addView(text("",3));body.addView(button("Scan struk",scanner::choose));body.addView(text("",3));body.addView(button("Tambah pemasukan",()->edit(null,"income")));body.addView(text("Saldo ini berasal dari catatan pribadi dan bersama di aplikasi, bukan saldo bank. Perubahan bersama yang masih menunggu belum mengubah saldo tersimpan.",13));}
 void transactions(){body.addView(button("Tambah transaksi",()->edit(null,"expense")));body.addView(text("",3));body.addView(button("Scan struk",scanner::choose));list(false);}
 String scope(JSONObject r){return r.optString("visibility").equals("shared")?"Bersama":"Pribadi · hanya ponsel ini";}
 void list(boolean trash){int count=0;for(Store.Row r:store.all()){JSONObject j=r.display();if(j.optBoolean("deleted")!=trash||j.optString("kind").equals("shopping"))continue;count++;String state=r.conflict!=null?"Perubahan berbenturan":r.pending!=null?"Menunggu sinkronisasi":"Tersimpan";TextView row=text(j.optString("title")+"\n"+money(j.optLong("amount"))+" · "+(j.optString("kind").equals("income")?"Pemasukan":"Pengeluaran")+"\n"+prettyDate(j.optString("date"))+" · "+scope(j)+"\n"+state+(j.optString("updatedBy").isEmpty()?"":" · oleh "+j.optString("updatedBy")),15);row.setPadding(dp(12),dp(12),dp(12),dp(12));row.setOnClickListener(v->{if(r.pending!=null){pendingDialog(r);return;}if(trash){changeDeleted(r,false);return;}if(!j.optString("receipt").isEmpty()){try{new ReceiptReview(this).show(new JSONObject(j.optString("receipt")),r.photo,r.hash,r);}catch(Exception e){message("Rincian struk tidak dapat dibuka.");}}else edit(r,j.optString("kind"));});body.addView(row);}if(count==0)body.addView(text(trash?"Sampah kosong.":"Belum ada transaksi.",16));}
 Spinner visibility(LinearLayout f,Store.Row old){f.addView(text("Akses catatan",14));Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Pribadi — di ponsel ini","Bersama — Google Sheets"}));s.setSelection(old==null?0:old.display().optString("visibility").equals("shared")?1:0);if(old!=null)s.setEnabled(false);f.addView(s);return s;}
 Button dateButton(LinearLayout f,String[] value){Button b=new Button(this);Runnable label=()->b.setText(value[0].isEmpty()?"Pilih tanggal (belum terbaca)":prettyDate(value[0]));label.run();b.setOnClickListener(v->{Calendar c=Calendar.getInstance();if(!value[0].isEmpty()){String[] parts=value[0].split("-");c.set(Integer.parseInt(parts[0]),Integer.parseInt(parts[1])-1,Integer.parseInt(parts[2]));}new DatePickerDialog(this,(view,y,m,d)->{value[0]=String.format(Locale.ROOT,"%04d-%02d-%02d",y,m+1,d);label.run();},c.get(1),c.get(2),c.get(5)).show();});f.addView(b);return b;}
 void edit(Store.Row old,String kind){JSONObject j=old==null?new JSONObject():old.display();LinearLayout f=form();EditText name=input(f,"Judul",j.optString("title"),false),amount=input(f,"Nominal Rupiah",old==null?"":j.optString("amount"),true);Spinner type=new Spinner(this);type.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Pengeluaran","Pemasukan"}));type.setSelection(kind.equals("income")?1:0);f.addView(type);String[] date={j.optString("date",today())};dateButton(f,date);EditText category=input(f,"Kategori (boleh diubah)",j.optString("category","Belanja"),false),note=input(f,"Catatan",j.optString("note"),false);Spinner scope=visibility(f,old);
  AlertDialog d=dialog(old==null?"Catat transaksi":"Ubah transaksi",f,"Simpan");if(old!=null)f.addView(button("Hapus ke sampah",()->confirm("Hapus catatan? Dapat dipulihkan dari Pengaturan.",()->{changeDeleted(old,true);d.dismiss();})));d.getButton(-1).setOnClickListener(v->{try{String title=validTitle(name);long n=requiredMoney(amount);if(category.length()>80||note.length()>16000)throw new IllegalArgumentException("Kategori atau catatan terlalu panjang.");JSONObject r=Store.make(title,n,type.getSelectedItemPosition()==1?"income":"expense",date[0],scope.getSelectedItemPosition()==1?"shared":"private",note.getText().toString(),category.getText().toString(),"");if(old!=null){r.put("uuid",old.id);r.put("version",old.accepted.optLong("version",0));}save(r,old==null?"":old.photo,old==null?"":old.hash);d.dismiss();}catch(Exception e){message(e.getMessage());}});
 }
 String validTitle(EditText e){String s=e.getText().toString().trim();if(s.isEmpty()||s.length()>120){e.setError("Isi judul, maksimal 120 karakter");throw new IllegalArgumentException("Periksa judul.");}return s;}
 Long optionalMoney(EditText e){String s=e.getText().toString().trim();if(s.isEmpty())return null;Long n=ReceiptParser.money(s);if(n==null){e.setError("Masukkan Rupiah utuh tanpa tanda minus");throw new IllegalArgumentException("Periksa nominal.");}return n;}
 long requiredMoney(EditText e){Long n=optionalMoney(e);if(n==null||n<=0){e.setError("Nominal harus lebih dari nol");throw new IllegalArgumentException("Isi nominal Rupiah.");}return n;}
 void save(JSONObject r,String photo,String hash){if(r.optString("visibility").equals("shared")&&!cloud.connected())throw new IllegalStateException("Hubungkan Google Sheets di Pengaturan untuk catatan bersama.");store.save(r,photo,hash);screen();sync();}
 void confirm(String msg,Runnable action){AlertDialog d=new AlertDialog.Builder(this).setMessage(msg).setNegativeButton("Batal",null).setPositiveButton("Lanjutkan",(a,b)->{try{action.run();}catch(Exception e){message(e.getMessage());}}).create();show(d);}
 void changeDeleted(Store.Row r,boolean deleted){try{JSONObject j=Store.wire(r.display());j.put("deleted",deleted);j.put("version",r.accepted.optLong("version",0));save(j,r.photo,r.hash);}catch(Exception e){message(e.getMessage());}}
 void pendingDialog(Store.Row r){if(r.conflict!=null){String msg="Versi Anda: "+r.pending.optString("title")+" · "+money(r.pending.optLong("amount"))+"\nVersi bersama: "+r.conflict.optString("title")+" · "+money(r.conflict.optLong("amount"))+"\n\nMemakai versi Anda mengganti seluruh catatan bersama.";LinearLayout f=form();f.addView(text(msg,15));f.addView(text(describe(r.pending)+"\n\n"+describe(r.conflict),14));ScrollView scroll=new ScrollView(this);scroll.addView(f);show(new AlertDialog.Builder(this).setTitle("Tinjau perubahan").setView(scroll).setNegativeButton("Nanti",null).setNeutralButton("Pakai bersama",(a,b)->{store.resolve(r.id,false);screen();}).setPositiveButton("Pakai versi saya",(a,b)->{store.resolve(r.id,true);sync();}).create());}else show(new AlertDialog.Builder(this).setTitle("Menunggu tersimpan").setMessage("Catatan aman di ponsel. Sambungkan internet lalu coba sinkronkan. "+(r.error==null?"":r.error)).setNegativeButton("Tutup",null).setNeutralButton("Batalkan perubahan",(a,b)->confirm("Batalkan perubahan yang belum tersimpan?",()->{if(busy){message("Tunggu sinkronisasi selesai.");return;}store.discardPending(r.id);screen();})).setPositiveButton("Sinkronkan",(a,b)->sync()).create());}
 String describe(JSONObject j){return j.optString("title")+"\n"+money(j.optLong("amount"))+"\nTanggal: "+prettyDate(j.optString("date"))+"\nKategori: "+j.optString("category")+"\nCatatan: "+j.optString("note")+"\nDihapus: "+(j.optBoolean("deleted")?"Ya":"Tidak")+"\nRincian: "+j.optString("receipt","Tidak ada");}
 void plans(){SharedPreferences p=getSharedPreferences("settings",0);long target=p.getLong("target",0),saved=p.getLong("saved",0);card("Target tabungan pribadi",money(target));card("Dana dialokasikan",money(saved));body.addView(text("Kekurangan: "+money(Math.max(0,target-saved))+"\nAlokasi tidak dihitung sebagai pengeluaran. Target ini masih tersimpan di ponsel.",16));body.addView(button("Atur target dan alokasi",()->{LinearLayout f=form();EditText t=input(f,"Target Rupiah",Long.toString(target),true),s=input(f,"Dana dialokasikan",Long.toString(saved),true);AlertDialog d=dialog("Target tabungan",f,"Simpan");d.getButton(-1).setOnClickListener(v->{try{Long a=optionalMoney(t),b=optionalMoney(s);if(a==null||b==null)throw new IllegalArgumentException("Isi kedua nominal.");p.edit().putLong("target",a).putLong("saved",b).apply();d.dismiss();}catch(Exception e){message(e.getMessage());}});}));}
 void shopping(){body.addView(button("Tambah barang",()->{LinearLayout f=form();EditText n=input(f,"Nama dan jumlah barang","",false);Spinner scope=visibility(f,null);AlertDialog d=dialog("Daftar belanja",f,"Tambah");d.getButton(-1).setOnClickListener(v->{try{save(Store.make(validTitle(n),0,"shopping","",scope.getSelectedItemPosition()==1?"shared":"private","","Belanja",""),"","");d.dismiss();}catch(Exception e){message(e.getMessage());}});}));for(Store.Row r:store.all()){JSONObject j=r.display();if(!j.optString("kind").equals("shopping")||j.optBoolean("deleted"))continue;CheckBox item=new CheckBox(this);item.setText(j.optString("title")+"\n"+scope(j)+(r.pending!=null?" · Menunggu":""));item.setTextSize(16);item.setMinHeight(dp(60));item.setChecked(j.optLong("amount")==1);item.setOnClickListener(v->{if(r.pending!=null){item.setChecked(j.optLong("amount")==1);pendingDialog(r);return;}try{JSONObject x=Store.wire(j);x.put("amount",item.isChecked()?1:0);x.put("version",r.accepted.optLong("version",0));save(x,r.photo,r.hash);}catch(Exception e){message(e.getMessage());item.setChecked(j.optLong("amount")==1);}});item.setOnLongClickListener(v->{confirm("Hapus barang ini?",()->changeDeleted(r,true));return true;});body.addView(item);}body.addView(text("Mencentang barang tidak membuat pengeluaran. Catat pembayaran sekali melalui transaksi atau Scan Struk.",14));}
 void settings(){body.addView(button(cloud.connected()?"Kelola koneksi pasangan":"Hubungkan Google Sheets",()->new ConnectionScreen(this).show()));body.addView(text("",3));body.addView(button("Sinkronkan sekarang",this::sync));body.addView(text("",3));body.addView(button("Pilih foto layar pembuka",()->pick("image/*",102)));body.addView(text("",3));body.addView(button("Ekspor transaksi CSV",this::export));body.addView(text("",3));body.addView(button("Impor CSV versi 0.3",()->pick("*/*",103)));body.addView(text("Versi native 0.4 beta. OCR berjalan di ponsel. Catatan bersama dan rincian struk dikirim ke Google Sheets setelah koneksi aktif. Foto bukti, catatan pribadi, dan target tabungan masih di ponsel. Simpan salinan foto asli di galeri.\n\nLogin Google/ChatGPT, iPhone, dompet, anggaran, dan pengingat belum tersedia dalam versi ini. Koneksi memakai kode perangkat pribadi.",14));body.addView(button("Petunjuk aktivasi Google Sheets",()->open("https://github.com/Siintelair-Unit-1/Langkah-Berdua/blob/main/docs/AKTIFKAN-GOOGLE-SHEETS.md")));body.addView(text("Pulihkan transaksi: ketuk catatan di bawah.",16));list(true);}
 void sync(){if(!cloud.connected()||busy||isDestroyed())return;busy=true;status="Menyinkronkan…";if(statusView!=null)statusView.setText(status+pendingLabel());worker.execute(()->{try{for(Store.Row row:store.all()){if(row.pending==null||row.conflict!=null||"INVALID".equals(row.error))continue;JSONObject r=cloud.call(new JSONObject().put("action","save").put("opId",row.op).put("version",row.base).put("record",row.pending));if(r.optBoolean("ok"))store.ack(row.id,row.op,r.getJSONObject("record"));else if(r.optString("code").equals("CONFLICT"))store.conflict(row.id,row.op,r.optJSONObject("current"));else {store.failed(row.id,row.op,r.optString("code"));if(r.optString("code").equals("AUTH"))cloud.p.edit().putBoolean("connected",false).commit();throw new IOException(r.optString("error"));}}
   JSONObject r=cloud.call(new JSONObject().put("action","sync"));if(!r.optBoolean("ok")){if(r.optString("code").equals("AUTH"))cloud.p.edit().putBoolean("connected",false).commit();throw new IOException(r.optString("error"));}store.pull(r.getJSONArray("records"));status="Tersinkron "+new java.text.SimpleDateFormat("HH:mm",new Locale("id","ID")).format(new Date());
  }catch(Exception e){status=e.getMessage()==null?"Belum tersinkron. Catatan tetap di ponsel.":e.getMessage();}finally{busy=false;runOnUiThread(()->{if(isDestroyed())return;if(!showingSplash&&dialogs==0)screen();else if(statusView!=null)statusView.setText(status+pendingLabel());});}});}
 @Override public void ready(String raw,String path,String hash){try{ReceiptParser.Result p=ReceiptParser.parse(raw);JSONArray items=new JSONArray();for(ReceiptParser.Item i:p.items)items.put(new JSONObject().put("name",i.name).put("qty",i.qty).put("unit",i.unit).put("amount",i.amount));JSONObject r=new JSONObject().put("store",p.store).put("date",p.date).put("total",p.total).put("discount",p.discount).put("tax",p.tax).put("fee",p.fee).put("items",items).put("raw",raw.length()>12000?raw.substring(0,12000):raw);new ReceiptReview(this).show(r,path,hash,null);}catch(Exception e){message("Hasil struk tidak dapat dibuka. Coba foto lain.");}}
 void pick(String mime,int request){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType(mime);i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,request);}
 void open(String url){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){message("Tidak ada aplikasi untuk membuka tautan.");}}
 void export(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/csv");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,"Langkah-Berdua-"+today()+".csv");startActivityForResult(i,101);}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==201||request==202){scanner.result(request,result,data);return;}if(result!=RESULT_OK||data==null)return;try{if(request==102){getContentResolver().takePersistableUriPermission(data.getData(),Intent.FLAG_GRANT_READ_URI_PERMISSION);getSharedPreferences("settings",0).edit().putString("photo",data.getData().toString()).apply();message("Foto pembuka tersimpan di perangkat");}else if(request==101)new CsvBackup(this).export(data.getData());else if(request==103)new CsvBackup(this).importOld(data.getData());}catch(Exception e){message("File tidak dapat diproses: "+e.getMessage());}}
}
